name: Github Action flow to Docker hub

on:
  push:
    branches: [ main ]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazów na repozytorium
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME }}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-actions@v2
        with:
          contex: ./
          file: ./dockerfile.v1
          push : true
          tags: alpakasyberyjska/projekt2:ghfront1
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      
