# This is a basic workflow to help you get started with Actions

name: Github Action flow to Docker hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-push-images:
    name: Budowa i publikacja obrazów na repozytorium
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -name: Checkout code
      uses: actions/checkout@v2
      
      -name: Buildx set-up
      id: buildx
      uses: docker/setup-buildx-action@v1
      
      -name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME }}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      -name: Build and push
      id: docker_build
      uses: docker/build-push-actions@v2
      with:
        contex: ./
        file: ./dockerfile.v1
        push : true
        tags: alpakasyberyjska/projekt2:ghfront1
        
      -name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
        
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
